### ISSUE TITLE
Inclusão de Usuário

### ISSUE THREAD

**Issue by lucalves** [mecontrata/mecontrata.github.io#1]
Boa tarde,

Qual o modo para incluir meu usuário na homepage do mecontrata? Apenas enviar um pull request alterando o código ou há alguma regra incluída no repositório?

Seria interessante um arquivo readme com regras para quem tiver interesse em contribuir com o projeto!

Aguardo,

**Comment by rfoel** [comment]
Por enquanto eu pego os dados do [@frontendbr](https://github.com/frontendbr). Mais pra frente gostaria de incluir os dados do [@backendbr](https://github.com/backend-br) também, ou fazer algo unificado nesse repositório mesmo. Se quiser seu usuário na homepage é só entrar [aqui](https://github.com/frontendbr/me-contrata).

**Comment by lucalves** [comment]
Estou a disposição pra ajudar a unificar esse repositório.

De qualquer forma, vou incluir no @frontendbr.
Fechando a issue.
Obrigado!
